trigger:
- master

pr:
- master

jobs:
- job: Windows_x64
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    clean: true
    submodules: true
  - task: MSBuild@1
    inputs:
      solution: '*.sln'
      maximumCpuCount: true
      platform: 'x64'

- job: Windows_x86
  pool:
    vmImage: 'windows-latest'

  steps:
  - checkout: self
    clean: true
    submodules: true
  - task: MSBuild@1
    inputs:
      solution: '*.sln'
      maximumCpuCount: true
      platform: 'x86'
